export default {
  whatsPopular: "What's Popular",
  freeToWatch: 'Free To Watch',
  latestTrailers: 'Latest Trailers',
  trending: 'Trending',
  streaming: 'Streaming',
  onTv: 'On Tv',
  forRent: 'For Rent',
  inTheatres: 'In Theatres',
  movies: 'Movies',
  tv: 'TV',
  today: 'Today',
  thisWeek: 'This Week',
  overview: 'Overview',
  movieDB: 'MovieDB',
  homeScreen: 'Home Screen',
  detailsScreen: 'Details Screen',
  networkError: 'NETWORK_ERROR',
  internetCheck: 'Please check your internet connection',
  connectionError: 'CONNECTION_ERROR',
  serverError: 'SERVER_ERROR',
  serverUnavailable: 'Server is not available',
  somethingWrong: 'Something went wrong',
  noCache: 'no-cache',
};
